version: '3.8'

services:
  go-initializer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8181/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development services (optional)
  go-initializer-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8181:8181"
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - /app/backend/vendor
    environment:
      - GIN_MODE=debug
    profiles:
      - dev